"""Add Notification model

Revision ID: cd77741b634d
Revises: 
Create Date: 2026-01-15 19:35:28.911118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd77741b634d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('RefundRequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event'))
        batch_op.drop_index(batch_op.f('idx_order'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_ticket'))
        batch_op.drop_index(batch_op.f('idx_user'))

    op.drop_table('RefundRequest')
    with op.batch_alter_table('Discount', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('discount_code'))
        batch_op.drop_index(batch_op.f('idx_active'))
        batch_op.drop_index(batch_op.f('idx_code'))
        batch_op.create_index(batch_op.f('ix_Discount_discount_code'), ['discount_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_Discount_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_category'))
        batch_op.drop_index(batch_op.f('idx_featured'))
        batch_op.drop_index(batch_op.f('idx_start_date'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_venue'))
        batch_op.create_index(batch_op.f('ix_Event_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Event_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_Event_start_datetime'), ['start_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_Event_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_Event_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('EventCategory', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_active'))
        batch_op.create_index(batch_op.f('ix_EventCategory_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('paid_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_order_code'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_user'))
        batch_op.drop_index(batch_op.f('order_code'))
        batch_op.create_index(batch_op.f('ix_Order_order_code'), ['order_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_Order_order_status'), ['order_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_Order_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.alter_column('payment_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('CREDIT_CARD', 'BANK_TRANSFER', 'E_WALLET', 'MOMO', 'VNPAY', 'CASH', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('payment_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_order'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('order_id'))
        batch_op.drop_index(batch_op.f('payment_code'))
        batch_op.create_index(batch_op.f('ix_Payment_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_Payment_payment_code'), ['payment_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_Payment_payment_status'), ['payment_status'], unique=False)

    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_event'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_user'))
        batch_op.create_index(batch_op.f('ix_Review_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Review_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_Review_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('role_name'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('Seat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Seat_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_Seat_ticket_type_id'), ['ticket_type_id'], unique=False)

    with op.batch_alter_table('Ticket', schema=None) as batch_op:
        batch_op.alter_column('checked_in_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_order'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_ticket_code'))
        batch_op.drop_index(batch_op.f('idx_ticket_seat'))
        batch_op.drop_index(batch_op.f('ticket_code'))
        batch_op.create_index(batch_op.f('ix_Ticket_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Ticket_ticket_code'), ['ticket_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_Ticket_ticket_status'), ['ticket_status'], unique=False)

    with op.batch_alter_table('TicketType', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_active'))
        batch_op.drop_index(batch_op.f('idx_event'))
        batch_op.create_index(batch_op.f('ix_TicketType_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_TicketType_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_active'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_active'))
        batch_op.drop_index(batch_op.f('idx_city'))
        batch_op.drop_index(batch_op.f('ix_venue_status'))
        batch_op.create_index(batch_op.f('ix_Venue_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_Venue_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_Venue_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Venue_status'))
        batch_op.drop_index(batch_op.f('ix_Venue_is_active'))
        batch_op.drop_index(batch_op.f('ix_Venue_city'))
        batch_op.create_index(batch_op.f('ix_venue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('idx_active'), ['is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_is_active'))
        batch_op.drop_index(batch_op.f('ix_User_email'))
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('TicketType', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TicketType_is_active'))
        batch_op.drop_index(batch_op.f('ix_TicketType_event_id'))
        batch_op.create_index(batch_op.f('idx_event'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_active'), ['is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('Ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Ticket_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_Ticket_ticket_code'))
        batch_op.drop_index(batch_op.f('ix_Ticket_order_id'))
        batch_op.create_index(batch_op.f('ticket_code'), ['ticket_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_ticket_seat'), ['seat_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ticket_code'), ['ticket_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['ticket_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_order'), ['order_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('checked_in_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('Seat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Seat_ticket_type_id'))
        batch_op.drop_index(batch_op.f('ix_Seat_status'))

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_index(batch_op.f('role_name'), ['role_name'], unique=True)
        batch_op.alter_column('role_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)

    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Review_user_id'))
        batch_op.drop_index(batch_op.f('ix_Review_status'))
        batch_op.drop_index(batch_op.f('ix_Review_event_id'))
        batch_op.create_index(batch_op.f('idx_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_event'), ['event_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Payment_payment_status'))
        batch_op.drop_index(batch_op.f('ix_Payment_payment_code'))
        batch_op.drop_index(batch_op.f('ix_Payment_order_id'))
        batch_op.create_index(batch_op.f('payment_code'), ['payment_code'], unique=True)
        batch_op.create_index(batch_op.f('order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_order'), ['order_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('CREDIT_CARD', 'BANK_TRANSFER', 'E_WALLET', 'MOMO', 'VNPAY', 'CASH', collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('payment_code',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Order_user_id'))
        batch_op.drop_index(batch_op.f('ix_Order_order_status'))
        batch_op.drop_index(batch_op.f('ix_Order_order_code'))
        batch_op.create_index(batch_op.f('order_code'), ['order_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['order_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_code'), ['order_code'], unique=False)
        batch_op.alter_column('paid_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('EventCategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_EventCategory_is_active'))
        batch_op.create_index(batch_op.f('idx_active'), ['is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Event_venue_id'))
        batch_op.drop_index(batch_op.f('ix_Event_status'))
        batch_op.drop_index(batch_op.f('ix_Event_start_datetime'))
        batch_op.drop_index(batch_op.f('ix_Event_is_featured'))
        batch_op.drop_index(batch_op.f('ix_Event_category_id'))
        batch_op.create_index(batch_op.f('idx_venue'), ['venue_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_start_date'), ['start_datetime'], unique=False)
        batch_op.create_index(batch_op.f('idx_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('idx_category'), ['category_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('Discount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Discount_is_active'))
        batch_op.drop_index(batch_op.f('ix_Discount_discount_code'))
        batch_op.create_index(batch_op.f('idx_code'), ['discount_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('discount_code'), ['discount_code'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('RefundRequest',
    sa.Column('refund_request_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('processed_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], name=op.f('RefundRequest_ibfk_4'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], name=op.f('RefundRequest_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['Ticket.ticket_id'], name=op.f('RefundRequest_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name=op.f('RefundRequest_ibfk_3')),
    sa.PrimaryKeyConstraint('refund_request_id')
    )
    with op.batch_alter_table('RefundRequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ticket'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_order'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_event'), ['event_id'], unique=False)

    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Notification_user_id'))

    op.drop_table('Notification')
    # ### end Alembic commands ###
